board = []



for y in range(0,6,1):
    board.append([])
    for x in range (0, 7, 1):
        board[y].append("[.]")
for y in (board):
    for x in y:
        print (x, end = "")
    print()
userInput=input("choose a column to put your piece into (between 1 and 7")
if not int(userInput) in (1,2,3,4,5,6,7):
    print ("your position is invalid. please insert a new position")
if userInput in (1,2,3,4,5,6,7)
    
    
